default: &default
  encoding: utf8
  adapter: mysql2
  timeout: 5000
  host: 127.0.0.1
  port: 3306
  password:
  pool: 5

development:
  <<: *default
  database: xuan_eat_development

test:
  <<: *default
  database: xuan_eat_test

production:
  <<: *default
  host: ec2-54-197-253-142.compute-1.amazonaws.com
  database: d6vl78d3lc581i
  user: ssumsfuqyluwwy
  port: 5432
  password: G26FG0UK2kOZvmjUIo_QDkyu9V
  adapter: postgresql
