# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 299e809d3ece9f0b06ddfe380352b5a8a3f7a6b724c89c40a2f22c473a48ba161c43e47c683d078234c85c9d3e0e9c05d2ed5f931bdf7f9b4cf38c969d8d98e1

test:
  secret_key_base: f143a26c5d3948950f271306144b60c88469ba15ae5262a57fa12d92a8acb8a141fc58fe039aa87a816fd076458c290cc324811b2f202b5e0ca65f0cb7d767d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
